### ISSUE TITLE
Gameplay

### ISSUE THREAD

**Issue by Pitmairen** [hials/HTML5-GroupProject#1]
We need a detailed description of how the game should work. 
-How the player kills the enemies.
-What happens if an enemy touches the player?
and so on ...

**Comment by TMHolen95** [comment]
I can create a document with the details in depth soon. 
But in response to the two points stated above:
Player kills enemy by a hit attack, I'll provide a graphic element for attack effect, at a later point in time.
If enemy touches player, player is stunned for x-seconds depending upon which enemy touched.
Enemies attempts to reach player house, if touched player house loses 1-2 hp.Player house has 30 hp.
I'll also provide the house image, later.

**Comment by hasirak** [comment]
Started work on a document containing the ruleset of the mechanics.
You can find it here:
https://docs.google.com/document/d/1eQs9dvZaS2tfNn6ZJtD5YFU8PY6sqQJWrKK4XoPR7Rw/edit?usp=sharing

**Comment by hasirak** [comment]
On second thought, let's try to keep it all in Git.
Removed the Google document, and added the rules to "GameSpecification.txt" instead.
