### ISSUE TITLE
The enemy spawner is too eager to spawn new enemies.

### ISSUE THREAD

**Issue by Pitmairen** [hials/HTML5-GroupProject#9]
The enemy spawner is a little bit too eager to spawn new enemies: :)

![spawner](https://cloud.githubusercontent.com/assets/357032/6674141/0a1379a8-cc18-11e4-9adb-0aabcb9d7f2f.png)

**Comment by TMHolen95** [comment]
Working on it :-)

**Comment by TMHolen95** [comment]
Spawner is now finished, will mark issue as closed :-)
